# Generated by Django 4.2 on 2024-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_region_nombre_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='nombre_region',
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
