# Generated by Django 4.2 on 2024-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_region_nombre_region_region_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('No Disponible', 'No disponible')], unique=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre_inmueble',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='tipo',
            field=models.CharField(choices=[('Arrendador', 'Arrendador'), ('Arrendatario', 'Arrendatario')], unique=True),
        ),
    ]
