# Generated by Django 4.2 on 2024-06-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_inmueble_descripcion_alter_inmueble_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')]),
        ),
    ]
