# Generated by Django 4.2 on 2024-06-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_region_region_nombre_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='correo_electronico',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='telefono_personal',
            new_name='telefono',
        ),
    ]
