# Generated by Django 4.2 on 2024-06-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_correo_electronico_perfil_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='cantidad_de_Habitaciones',
            new_name='cant_de_banos',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='cantidad_de_banos',
            new_name='cant_de_estac',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='cantidad_de_estacionamientos',
            new_name='cant_de_hab',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='m2_Totales_o_del_terreno',
            new_name='m2_totales',
        ),
    ]
