# Generated by Django 4.2 on 2024-06-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_cantidad_de_habitaciones_inmueble_cant_de_banos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='id_inmueble',
            new_name='id_tipo_inmueble',
        ),
    ]
