# Generated by Django 4.2 on 2024-06-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_inmueble_descripcion_alter_inmueble_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
