# Generated by Django 4.2 on 2024-06-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_inmueble_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual_de_arriendo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
