# Generated by Django 4.2 on 2024-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_inmueble_precio_mensual_de_arriendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='nombre_inmueble',
            field=models.CharField(max_length=50),
        ),
    ]
